# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: BOOTSTRAP_HASKELL_GHC_VERSION
  value: 9.2.5
- name: BOOTSTRAP_HASKELL_CABAL_VERSION
  value: 3.8.1.0
# - name: BOOTSTRAP_HASKELL_STACK_VERSION
#   value: 2.9.3
- name: GHCUP_INSTALL_BASE_PREFIX
  value: $(Pipeline.Workspace)
- name: GHCUP_CACHE_FOLDER
  value: $(Pipeline.Workspace)/.ghcup
- name: STACK_CACHE_FOLDER
  value: /home/vsts/.stack

steps:
- task: Cache@2
  inputs:
    key: '"ghcup3"'
    path: $(GHCUP_CACHE_FOLDER)
  displayName: Get GHCUP installation from cache

- task: Cache@2
  inputs:
    key: '"stack1"'
    path: $(STACK_CACHE_FOLDER)
  displayName: Test caching stack compilation of dependencies

- script: |
    sudo apt-get update && \
    sudo apt-get install -y build-essential curl libffi-dev libffi8ubuntu1 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5 && \
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_INSTALL_STACK=1 BOOTSTRAP_HASKELL_ADJUST_BASHRC=P sh
  displayName: 'Install Haskell, Cabal and Stack'

- script: |
    stack test
  displayName: 'Run tests'
